---
abstract: 'DateTime Extension for Calculating Important Chinese Dates'
author:
  - 'Daisuke Maki C<< <daisuke@endeworks.jp> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Event-Chinese
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DateTime::Astro: 0
  Math::Round: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lestrrat/DateTime-Event-Chinese.git
version: 0.99999
