--- #YAML:1.0
name: DateTime-Event-Chinese
version: 0.01
license: perl
distribution_type: module
requires:
  DateTime: 0
  DateTime::Event::Lunar: 0
  DateTime::Event::SolarTerm: 0
  DateTime::Set: 0
  Params::Validate: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Event::Chinese:
    file: lib/DateTime/Event/Chinese.pm
    version: 0.01
generated_by: Module::Build version 0.21
